version: '3.4'

services:
  redis:
    image: redis
    command: redis-server --requirepass FIBONACCI
    ports:
      - 6379:6379
  fibonacci:
    image: fibonacci
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    links:
      - redis

